### PR TITLE
omg i hope this works

### PR DESCRIPTION
**Pull request by githubschman**
(intro is currently turned on for non mobile windows,  but we can turn that off for deployment)

### CODE REVIEW

**Review by brkwtz — DISMISSED** [review]
Intro looks so cute in mobile and the home page element sizing looks awesome in mobile!

There are a few things that are a little broken in this branch:
1. In mobile, the background is now the brown scroll background, which doesn't cover the entire page. We should be using the spiderwebs background.
2. Intro does not play in desktop BUT the skip intro button pops up anyway and there is a timeout before reaching /coven. Intro should either play in desktop or be totally removed in desktop.
3. Looks like logic to prevent undefined titles has been removed in the Home component.

I'd suggest merging master to your branch before pulling again as there appear to be other discrepancies as well, e.g. levelup animation doesn't show and some styling is different.

Let me know if you have questions!

**Comment by githubschman** [comment]
> Intro does not play in desktop BUT the skip intro button pops up anyway and there is a timeout before reaching /coven. Intro should either play in desktop or be totally removed in desktop.

in intro.jsx i have this, just for testing!
// if(!this.mobilePlayer){this.props.router.push('/coven')}
// comment line 21 back in for deployment...

**Comment by githubschman** [comment]
made rachel's changes

**Comment by githubschman** [comment]
added 8bit background to waiting room

**Review by hibetty — COMMENTED** [review]
Looks great Sarah! Could you comment back in line 21 in Intro.jsx before we merge?

**Review by hibetty — APPROVED** [review]

**Pull request merged**
